.PHONY: clean all

CC=gcc
CFLAGS=-Wall -Wextra

all: fork1 p1 exec1 exec2 p3 exit1 exit2 wait1 read1 write1

fork1: fork1.c

p1: p1.c

exec1: exec1.c

exec2: exec2.c

p3: p3.c

exit1: exit1.c

exit2: exit2.c

wait1: wait1.c

read1: read1.c

write1: write1.c

clean:
	rm -f *.o fork1 p1 exec1 exec2 p3 exit1 exit2 wait1 read1 write1