.PHONY: clean all

CC=gcc
CFLAGS=-Wall -Wextra

all: kill1 sig1 sigact1 pipe1 pipe2 pipe3 pipe4 pipe5 pipe6 pipe7

kill1: kill1.c

sig1: sig1.c

sigact1: sigact1.c

pipe1: pipe1.c

pipe2: pipe2.c

pipe3: pipe3.c

pipe4: pipe4.c

pipe5: pipe5.c

pipe6: pipe6.c

pipe7: pipe7.c

clean:
	rm -f *.o pipe1 pipe2 pipe3 pipe4 pipe5 pipe6 pipe7 sig1 sigact1 kill1